# Generated by Django 5.0.4 on 2024-08-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_moviemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
