# Generated by Django 5.0.4 on 2024-08-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_moviemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
